### ISSUE TITLE
最新版本会导致zotero pane 左下角的tag栏无法加载出来，而且测试后发现确实是zoplicate导致的

### ISSUE THREAD

**Issue by ChinJCheung** [ChenglongMa/zoplicate#10]
<img width="399" alt="image" src="https://github.com/ChenglongMa/zoplicate/assets/47018950/a599cc4b-f868-4443-999c-537c6d350bb7">

**Comment by ChinJCheung** [comment]
测试1.1.0版本之后，可以正常加载

**Comment by ChenglongMa** [comment]
多谢反馈，明天我修复一下

**Comment by ChenglongMa** [comment]
@ChinJCheung,

感谢你的反馈，我已经修复了这个bug，请安装或升级 [v2.1.0](https://github.com/ChenglongMa/zoplicate/releases/tag/2.1.0) 查看.

谢谢！

**Comment by ChinJCheung** [comment]
感谢👍！
