### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by dschaehi** [ChenglongMa/zoplicate#119]
Hi @ChenglongMa, I just realized that selecting all items (~ 3000 items) and opening the context menu with the right mouse click leads to a very long delay.  Without Zoplicate, opening the context menu works instantly. Could you perhaps investigate this issue? I wonder whether there is an O(n^2) comparison algorithm running behind the scene, when the right mouse click is triggered.

**Comment by ChenglongMa** [comment]
Hi @dschaehi,

Thanks for your feedback! It's indeed a bug. I'm fixing it and will release the new version soon.

Sorry for the inconvenience!

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @dschaehi,

Thanks for your feedback. I have fixed this issue and released the new version.

Thank you for your continued support!

Best,
Chenglong

**Comment by dschaehi** [comment]
Works like charm. Thanks @ChenglongMa!
One minor thing: If I select all 3000 items and open the context menu with the right mouse click, I then see the Zoplicate menu appearing and then quickly disappearing in the context menu. This is very minor and removing this effect may not worth for an effort.

**Comment by ChenglongMa** [comment]
Thanks, @dschaehi. I thought you might not find it, haha. It's indeed a side effect of the current version.

But I've found a solution, will fix it in the next version.

Thanks for your patience and valuable feedback :)

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @dschaehi,

The "flashing" issue of the menu has been fixed.

Thanks for your feedback and continued support :)

Best,
Chenglong

**Comment by dschaehi** [comment]
Thanks, @ChenglongMa!
