### ISSUE TITLE
Merge item pane is cut off

### ISSUE THREAD

**Issue by vancleve** [ChenglongMa/zoplicate#120]
It appears that Zoplicate is causing the merge item pane to be cut off in a recent beta of Zotero.

![image](https://github.com/user-attachments/assets/4c13f017-bbb1-4721-919f-0a9de1d3bf8e)

https://forums.zotero.org/discussion/120261/7-0-11-beta-8-d57392d81-merge-item-pane-is-cut-off#latest

7.0.11-beta.8+d57392d81
Zoplicate 3.0.3

**Comment by ChenglongMa** [comment]
Hi @vancleve, 

Thanks for your feedback! I will fix it soon.

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @vancleve,

This issue has been fixed in the new version.

Thanks for your support :)

Best,
Chenglong
