### ISSUE TITLE
"DuplicateItems must have at least one item"

### ISSUE THREAD

**Issue by dstillman** [ChenglongMa/zoplicate#124]
We've gotten multiple reports in the Zotero Forums of people encountering this error during syncing and thinking it's a problem with Zotero itself:

https://forums.zotero.org/discussion/120366/
https://forums.zotero.org/discussion/120411/
https://forums.zotero.org/discussion/120439/ (with screenshot)
https://forums.zotero.org/discussion/comment/481588/#Comment_481588

Could you look into this and push a fix?

**Comment by ChenglongMa** [comment]
Oh, thanks for letting me know, @dstillman. I'll check and fix it soon!

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @dstillman,

I have fixed this issue. Thank you again for reporting this.

Best,
Chenglong
