### ISSUE TITLE
Adding too many duplication item at once causing the window to exceed the screen 一次添加太多条文献是重复会导致窗口超出屏幕，无法操作

### ISSUE THREAD

**Issue by clj1573** [ChenglongMa/zoplicate#23]
Adding too many duplication item at once causing the window to exceed the screen and making it impossible to operate
一次添加太多条文献是重复会导致窗口超出屏幕，无法操作
![image](https://github.com/ChenglongMa/zoplicate/assets/151982925/f587809c-6788-42a4-bb51-e73232856762)

**Comment by ChenglongMa** [comment]
感谢反馈，之前尝试解决过，看来还是有问题，等着我再仔细查查。

对于现在的问题，你可以去Duplicate window用一下Bulk merge（批量合并） 功能处理这些重复项。

感谢理解！

**Comment by clj1573** [comment]
> 感谢反馈，之前尝试解决过，看来还是有问题，等着我再仔细查查。
> 
> 对于现在的问题，你可以去Duplicate window用一下Bulk merge（批量合并） 功能处理这些重复项。
> 
> 感谢理解！

我不知道你最新版是否解决了这个问题，我的zotero是6.0.35版，zoplicate用的是 0.6.1 版

**Comment by ChenglongMa** [comment]
哦哦，我是在 Zotero 7 的版本中解决的这一问题，Zoplicate的版本是 [v2.0.0](https://github.com/ChenglongMa/zoplicate?tab=readme-ov-file#v200).

由于 Zotero 7 马上发布，我个人时间也有限，所以 Zotero 6 的版本没有同步这些新功能。

非常抱歉！
