### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by vancleve** [ChenglongMa/zoplicate#30]
See <https://forums.zotero.org/discussion/113107/zotero-7-beta-bug-memory-leak-in-pdf-search>

**Comment by ChenglongMa** [comment]
Hi @vancleve,

Thank you so much for bringing this up! I will fix it soon.

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @vancleve,

Thank you for your help.

I'll inspect it first to see if I can find any clues.

Thanks,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @vancleve,

Thanks for your patience! I have finally fixed the memory leak issue.

Please update the plugin to [v3.0.0](https://github.com/ChenglongMa/zoplicate/releases/tag/3.0.0).

Thank you so much!

Best,
Chenglong

**Comment by vancleve** [comment]
thanks
