### ISSUE TITLE
Automatic duplicate detection is too fast 

### ISSUE THREAD

**Issue by tommyhosman** [ChenglongMa/zoplicate#43]
I appreciate the plugin!

There are instances when I save a link to zotero before I have access to the pdf (due to login permissions). After getting access to the pdf I try to save to zotero again. However by the time the zotero browser extension finds and saves the pdf to zotero, the plugin has already marked it as a duplicate. Therefore the item with the pdf entry remains in the trash.

If I take it out of the trash and manually run zoplicate, it chooses the right item with the pdf to keep. 

I have options set: `Keep Others` and `Most Detailed`.
Zoplicate: 3.0.2
Zotero: 7.0.0-beta.80

My thoughts are either waiting a bit or listening for attachment updates.

**Comment by ChenglongMa** [comment]
Good point@tommyhosman!

Thanks for your advice. I'll check it and fix this issue soon :)

**Comment by ChenglongMa** [comment]
Hi, this issue has been solved in the new version [v3.0.3](https://github.com/ChenglongMa/zoplicate/releases/tag/3.0.3).

Thanks for your attention. Please let me know if you have other questions 😊
