### ISSUE TITLE
Is it possible to add the option of dragging previous items to the current collection for detected duplicate items?

### ISSUE THREAD

**Issue by ChinJCheung** [ChenglongMa/zoplicate#5]
Paper 1 is currently in Collection 1. When attempting to add Paper 1 to Collection 2, a Duplicate Dialog will appear. To proceed, I need to keep the other items and drag Paper 1 into Collection 2.

the last result:

collection 1 :Paper 1
collection 2 :Paper 1

**Comment by ChenglongMa** [comment]
Hi @ChinJCheung,

Good suggestion! I will update this feature in the next version.
Thanks!

**Comment by ChenglongMa** [comment]
Hi @ChinJCheung,

Thanks for your advice. We have released the new version.

Please check the [Changelog](https://github.com/ChenglongMa/zoplicate/releases/tag/1.1.0) for the details.

Thanks!

**Comment by ChinJCheung** [comment]
thank you!
