### ISSUE TITLE
新导入一个pdf无法保存附件在已有的条目中（当默认操作设置为保留已有的条目）

### ISSUE THREAD

**Issue by csdaboluo** [ChenglongMa/zoplicate#51]
就是说，新导入一个PDF，
然后软件会自动为新PDF生成一个条目
如果这时插件设置为保留已有的，
这个时候插件会自动删除这个新生成条目（连同这个PDF一起）

我想要的是，新导入一个PDF，但是条目信息还是用已有的条目信息，然后这个PDF就保存在之前已有的（老的）条目里面

**Comment by ChenglongMa** [comment]
感谢反馈，我正在写这个功能😊

**Comment by ChenglongMa** [comment]
你好，该问题已在新发布的 [v3.0.3](https://github.com/ChenglongMa/zoplicate/releases/tag/3.0.3) 中解决。

感谢关注！如有问题请随时联系我 😊
