### ISSUE TITLE
重复项导入界面优化

### ISSUE THREAD

**Issue by xqshen123** [ChenglongMa/zoplicate#53]
您好，我在批量导入大量文献时，确实会弹出重复项导入的选择提示，但是我的重复项太多，导致对话框很长，根本无法触及底部的apply等选项

**Comment by ChenglongMa** [comment]
@xqshen123 谢谢反馈！请问您使用的是 Zotero 6 还是 7？

我在 Zotero 7 中修复了这一问题，由于官方对6不再更新，所以我暂时只在维护7的Bug和功能。

**Comment by xqshen123** [comment]
那我明白了，我之前用的6，谢谢~

**Comment by ChenglongMa** [comment]
不客气！感谢您的关注和反馈 :)
