### ISSUE TITLE
忽略订阅

### ISSUE THREAD

**Issue by Raphael-Hao** [ChenglongMa/zoplicate#54]
zoplicate会提示对rss feed订阅里面有重复

**Comment by ChenglongMa** [comment]
@Raphael-Hao 您好，感谢反馈！可以提供更多信息或截图吗？比如：

1. 提示的重复是错误的吗？
2. 如果卸载或关掉 Zoplicate, Zotero自己会提示有重复吗？
3. 您期望 Zotero 不检查 RSS feed 的重复是吗？

谢谢您的关注！

**Comment by Raphael-Hao** [comment]
zoplicate不应该检查RSS feed，因为rss feed的内容无法被更改。

**Comment by ChenglongMa** [comment]
好的，我现在看一下

**Comment by ChenglongMa** [comment]
@Raphael-Hao 你好，你能给我一个能复现这个问题的 RSS URL 吗？谢谢！

**Comment by Raphael-Hao** [comment]
https://rss.arxiv.org/rss/cs.ai
这个应该就可以，但是什么时候会触发，我不太清楚

**Comment by ChenglongMa** [comment]
好的，多谢！

**Comment by ChenglongMa** [comment]
@Raphael-Hao 你好，我测试了以下方法：

1. 导入 [https://rss.arxiv.org/rss/cs.ai](https://rss.arxiv.org/rss/cs.ai)；
2. 导入两遍；
3. 先添加rss中任意一篇文章，然后导入该rss；

以上测试都没有触发。代码中也会屏蔽掉rss的feed类型的，目前没能复现。

另外请问你用的是 Zotero 7 还是 6？ 我以上测试都是在7上测试的。

我再仔细检查检查代码。
谢谢！

**Comment by Raphael-Hao** [comment]
因为rss会每天自动更新，不知道是不是和这个有关。我每天早上打开电脑就会触发。我是zotero 7.

**Comment by ChenglongMa** [comment]
你好，该问题已在新发布的 [v3.0.3](https://github.com/ChenglongMa/zoplicate/releases/tag/3.0.3) 中解决。

感谢关注！如有问题请随时联系我 😊
