### ISSUE TITLE
如何使得默认保留旧条目时，在zotero中选择此旧条目

### ISSUE THREAD

**Issue by pencilheart** [ChenglongMa/zoplicate#7]

**Comment by csdaboluo** [comment]
![image](https://github.com/ChenglongMa/zoplicate/assets/102726296/4a87cfef-803f-4990-a9c5-13ff4bc6b834)
设置里好像有

**Comment by pencilheart** [comment]
这个已经勾上了，遇到的问题是：添加新的重复条目后，zotero内选择的条目并不是旧条目。

**Comment by ChenglongMa** [comment]
感谢 @pencilheart @csdaboluo 二位的反馈，我改天修复一下bug。

圣诞节快乐🎅！

**Comment by ChenglongMa** [comment]
@pencilheart 你好，

我刚刚试了一下，选择 `[保留已有的]...` 时，是可以保留旧条目的信息的，我是这样做的：

1. 修改某文章的**标题**、**摘要**等信息;
2. 添加一条新的note;
3. 添加一个新的tag;
4. 复制该条目的DOI，通过这个按钮重新添加该条目：![Snipaste_2023-12-24_23-52-25](https://github.com/ChenglongMa/zoplicate/assets/33501679/3d65094d-4174-4e1c-89ce-d45d93f4900b)
   * 或用浏览器重新导入该条目;
5. 保留的条目依然会保存之前的修改信息(标题、摘要、Note、Tag)等;
6. 若修改设置为 `[保留最新的]...`，之前的修改将会被新的条目覆盖，但Note和Tag依然保留;

可以告诉我你的操作方式以方便复现该问题吗？

谢谢！

**Comment by pencilheart** [comment]
旧的条目信息确实可以保留。现在想要的功能是：在合并后在主界面自动选中旧条目。比如在浏览器中看到此文献，当点击“save to zotero”后，实现在zotero中自动跳转到旧重复条目那一行。

**Comment by ChenglongMa** [comment]
@pencilheart 
好的，稍后我添加一下这个功能，谢谢！

**Comment by ChenglongMa** [comment]
@pencilheart,

你好，我在 [2.0.0版本](https://github.com/ChenglongMa/zoplicate/releases/tag/2.0.0) 中修复了这一问题，请在Zotero中更新这一插件。
如果有其他问题欢迎联系我。

非常感谢！
