### ISSUE TITLE
期待能够对数据库中现有的文件进行重复检测

### ISSUE THREAD

**Issue by fnightly** [ChenglongMa/zoplicate#8]
对现有的文件进行重复检测

**Comment by ChenglongMa** [comment]
Hi @fnightly,

你好，非常感谢你的建议！

可以详细描述一下你想要的功能吗？与[Zotero自带的Duplicate检查功能](https://www.zotero.org/support/duplicate_detection)有什么区别吗？

谢谢！

**Comment by csdaboluo** [comment]
> Hi @fnightly,
> 
> 你好，非常感谢你的建议！
> 
> 可以详细描述一下你想要的功能吗？与[Zotero自带的Duplicate检查功能](https://www.zotero.org/support/duplicate_detection)有什么区别吗？
> 
> 谢谢！

好像是zotero自带的Duplicate检查功能，合并的时候特别慢，只能一个一个点，重复的文献多了，就不好弄了，之前有这个插件[ZoteroDuplicatesMerger](https://link.zhihu.com/?target=https%3A//github.com/frangoud/ZoteroDuplicatesMerger)，但是作者好像不更新了，zotero 7 用不了

**Comment by ChenglongMa** [comment]
好的，我看一下能不能加到这个插件里，谢谢分享！

**Comment by ChenglongMa** [comment]
@fnightly,

你好，我看了一下[ZoteroDuplicatesMerger](https://link.zhihu.com/?target=https%3A//github.com/frangoud/ZoteroDuplicatesMerger)的文档和代码，它主要实现两个功能：

1. Smart merge items: 这个好像是和自带的菜单里的 <kbd>Merge Items...</kbd> 功能一样？
   
   ![Snipaste_2023-12-26_09-58-56](https://github.com/ChenglongMa/zoplicate/assets/33501679/6a3ef000-ea4d-42ca-b025-c00c4a8b7c31)
2. Bulk merge items: 该操作是设置好 Master Item 选择标准后（如：最新的、最旧的、第一作者名字最长的），然后批量合并重复项是吧？

不知道我理解的对不对，或者和你期望的功能一样不一样？如果有其他建议，我也可以试着实现🙂

谢谢！

**Comment by csdaboluo** [comment]
> @csdaboluo,
> 
> 你好，我看了一下[ZoteroDuplicatesMerger](https://link.zhihu.com/?target=https%3A//github.com/frangoud/ZoteroDuplicatesMerger)的文档和代码，它主要实现两个功能：
> 
> 1. Smart merge items: 这个好像是和自带的菜单里的 Merge Items... 功能一样？
>    ![Snipaste_2023-12-26_09-58-56](https://private-user-images.githubusercontent.com/33501679/292781747-6a3ef000-ea4d-42ca-b025-c00c4a8b7c31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Njg4MDMsIm5iZiI6MTcwMzU2ODUwMywicGF0aCI6Ii8zMzUwMTY3OS8yOTI3ODE3NDctNmEzZWYwMDAtZWE0ZC00MmNhLWIwMjUtYzAwYzRhOGI3YzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA1MjgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZGQyOWJmNzg5OTI2NjNkZGVmNzZhMjM1NDRhOTIxMmU0YmQ1OTZmODIzOGMzNzZlMjQxN2Y1ZDc4ZTA3ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gv9eSVG-zKXLCdoFzjOOvO323WaVTIbH8ZAC_JYGq44)
> 2. Bulk merge items: 该操作是设置好 Master Item 选择标准后（如：最新的、最旧的、第一作者名字最长的），然后批量合并重复项是吧？
> 
> 不知道我理解的对不对，或者和你期望的功能一样不一样？如果有其他建议，我也可以试着实现🙂
> 
> 谢谢！

设置好 Master Item 选择标准后（如：最新的、最旧的、第一作者名字最长的），然后批量合并重复项是吧？

就是这个功能.

非常感谢大佬的工作！🙏

**Comment by ChenglongMa** [comment]
好的，我试一试🙂

**Comment by ChenglongMa** [comment]
@fnightly @csdaboluo,

你们好，我在 [2.0.0版本](https://github.com/ChenglongMa/zoplicate/releases/tag/2.0.0) 中添加了 `批量合并` 功能，请在Zotero中更新并使用。

使用中可参阅 [该操作步骤](https://github.com/ChenglongMa/zoplicate#bulk-merge)。

如有问题或其他修改意见，欢迎联系我 🙂。

谢谢！

**Comment by ChenglongMa** [comment]
各位好，由于该功能已经实现，我先把这个issue关了，如果有问题欢迎再联系我。

非常感谢各位的关注！
