### ISSUE TITLE
[bug]每次重启zotero后，设置中多出一个zoplicate的菜单

### ISSUE THREAD

**Issue by WangYe661** [ChenglongMa/zoplicate#81]
![image](https://github.com/user-attachments/assets/00801732-e70f-4019-8eb3-1f862ce92398)

使用版本
* zoplicate3.0.3
* zotero7.0

这个问题不一定是由您的插件产生的，其他插件也存在这一问题

**Comment by ChenglongMa** [comment]
@WangYe661, 感谢您的反馈，我研究一下这个问题！稍后给您回复。

**Comment by WangYe661** [comment]
我个人更倾向于是zotero的问题，我安装的好几个插件都出现了这个现象

王钟锐
________________________________
发件人: Chénglóng Mǎ ***@***.***>
发送时间: Sunday, August 11, 2024 7:00:41 PM
收件人: ChenglongMa/zoplicate ***@***.***>
抄送: YeWang ***@***.***>; Mention ***@***.***>
主题: Re: [ChenglongMa/zoplicate] [bug]每次重启zotero后，设置中多出一个zoplicate的菜单 (Issue #81)


@WangYe661<https://github.com/WangYe661>, 感谢您的反馈，我研究一下这个问题！稍后给您回复。

―

**Comment by ChenglongMa** [comment]
我刚刚跟开发团队反馈了，看看他们怎么说🙏

**Comment by pencilheart** [comment]
您好，此问题依旧存在 @ChenglongMa

**Comment by ChenglongMa** [comment]
@pencilheart 多谢反馈，我已找到问题所在，下一版本会修复🙏🏻，多谢关注！

**Comment by ChenglongMa** [comment]
谢谢大家反馈，该问题已修复，多谢支持！
