### ISSUE TITLE
与green frog 存在冲突

### ISSUE THREAD

**Issue by holderhe** [ChenglongMa/zoplicate#84]
在使用[green frog](https://github.com/redleafnew/zotero-updateifsE) 更新条目元数据时，本插件会误把更新的条目当做重复条目删掉，即最终会把所有重复条目删掉了没有保留下一份应有的条目，已复现多次。

**Comment by ChenglongMa** [comment]
多谢反馈，一会我调试一下

**Comment by ChenglongMa** [comment]
您好，我查了一下，这个bug的原因在于green frog更新条目的时候会先**下载一个新的**，然后修改信息，最后把它删掉。这个过程中 zoplicate 会判定为出现了重复条目。

我正在尝试解决这一问题，请耐心等待。
非常感谢！

**Comment by ChenglongMa** [comment]
您好 @holderhe ，green frog 已更新。该问题应该已解决，请重新试一下 🙏

谢谢！
