### ISSUE TITLE
右键菜单当文件太多的时候会卡住，能不能限制到100个以内才做处理

### ISSUE THREAD

**Issue by zzlb0224** [ChenglongMa/zoplicate#94]
右键菜单当文件太多的时候会卡住，能不能限制到100个以内才做处理

**Comment by ChenglongMa** [comment]
您好，可以详细解释一下哪个右键菜单吗？如果能截图的话就更好了，非常感谢！

**Comment by zzlb0224** [comment]
在选择条目的时候
在选择比较少的时候是正常的右键弹出。
![image](https://github.com/user-attachments/assets/3b4ec254-7cae-4c2a-b218-72cf45d6fc0c)
![image](https://github.com/user-attachments/assets/3d46686a-0688-4cb8-9faf-b196d5ca60cb)

当我选择整个库的时候，就卡着不能动了，有6000+条目
![image](https://github.com/user-attachments/assets/dbe9ab18-0eb7-41cb-8aaa-0fc5a3e585f8)

**Comment by ChenglongMa** [comment]
非常感谢您的反馈，过几天我优化一下代码，最近有些忙，下个版本修复这个 bug。

多谢🙏

**Comment by pencilheart** [comment]
+1，右键菜单弹出在多条目时需要很长时间，关闭插件后恢复正常。选择182个项目后右键会弹出空白的Zoplicate菜单。
<img width="367" alt="Xnip2024-11-26_10-56-38" src="https://github.com/user-attachments/assets/8794a833-0c06-4dc7-978f-40c586cf1ffd">
是否是此原因导致了多条目右键卡顿？

**Comment by ChenglongMa** [comment]
@pencilheart,

感谢反馈！是这个原因，选择过多的条目会造成数据库查询时间过长，所以会卡顿。我尽快修复这个bug，多谢支持！！
